=== nyakosandor/PHRO7RWebXML/PHRO7R_1015/PHRO7R_XMLSchemaGPT.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- ========= Saját egyszerű típusok ========= -->

    <!-- Általános szövegmező – EZ a kötelező sajatTipus -->
    <xs:simpleType name="sajatTipus">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Kódok: pl. EKod, FKod, SzKod, GyKod, VKod -->
    <xs:simpleType name="kodTipus">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Életkor 0–120 év között -->
    <xs:simpleType name="eletkorTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="120"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Csillag: 1–5 között -->
    <xs:simpleType name="csillagTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Pozitív egész (összeg, házszám, időtartam, stb.) -->
    <xs:simpleType name="pozitivEgészTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Dátum (gyakorlat kezdete) -->
    <xs:simpleType name="datumTipus">
        <xs:restriction base="xs:date"/>
    </xs:simpleType>

    <!-- ========= Összetett típusok ========= -->

    <!-- Cím: Varos, Utca, Hazszam -->
    <xs:complexType name="cimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="sajatTipus"/>
            <xs:element name="Utca" type="sajatTipus"/>
            <xs:element name="Hazszam" type="pozitivEgészTipus"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Rendelés -->
    <xs:complexType name="rendelesTipus">
        <xs:sequence>
            <xs:element name="Osszeg" type="pozitivEgészTipus"/>
            <xs:element name="Etel" type="sajatTipus"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Rendelések gyűjteménye -->
    <xs:complexType name="rendelesekTipus">
        <xs:sequence>
            <xs:element name="Rendeles" type="rendelesTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Főszakács -->
    <xs:complexType name="foszakacsTipus">
        <xs:sequence>
            <xs:element name="Nev" type="sajatTipus"/>
            <xs:element name="Eletkor" type="eletkorTipus"/>
            <!-- több végzettség is lehet -->
            <xs:element name="Vegzettseg" type="sajatTipus" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="FKod" type="kodTipus" use="required"/>
    </xs:complexType>

    <!-- Szakács -->
    <xs:complexType name="szakacsTipus">
        <xs:sequence>
            <xs:element name="Nev" type="sajatTipus"/>
            <xs:element name="Reszleg" type="sajatTipus"/>
            <xs:element name="Vegzettseg" type="sajatTipus" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="SzKod" type="kodTipus" use="required"/>
    </xs:complexType>

    <!-- Szakácsok gyűjteménye -->
    <xs:complexType name="szakacsokTipus">
        <xs:sequence>
            <xs:element name="Szakacs" type="szakacsTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Gyakornok -->
    <xs:complexType name="gyakornokTipus">
        <xs:sequence>
            <xs:element name="Nev" type="sajatTipus"/>
            <xs:element name="Gyakorlat" type="sajatTipus"/>
            <xs:element name="Kezdete" type="datumTipus"/>
            <xs:element name="Idotartama" type="pozitivEgészTipus"/>
            <!-- több műszak is lehet -->
            <xs:element name="Muszak" type="sajatTipus" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="GyKod" type="kodTipus" use="required"/>
    </xs:complexType>

    <!-- Gyakornokok gyűjteménye -->
    <xs:complexType name="gyakornokokTipus">
        <xs:sequence>
            <xs:element name="Gyakornok" type="gyakornokTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Vendég -->
    <xs:complexType name="vendegTipus">
        <xs:sequence>
            <xs:element name="Nev" type="sajatTipus"/>
            <xs:element name="Eletkor" type="eletkorTipus"/>
            <xs:element name="Cim" type="cimTipus"/>
            <xs:element name="Rendelesek" type="rendelesekTipus"/>
        </xs:sequence>
        <xs:attribute name="VKod" type="kodTipus" use="required"/>
    </xs:complexType>

    <!-- Vendégek gyűjteménye -->
    <xs:complexType name="vendegekTipus">
        <xs:sequence>
            <xs:element name="Vendeg" type="vendegTipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Étterem -->
    <xs:complexType name="etteremTipus">
        <xs:sequence>
            <xs:element name="Nev" type="sajatTipus"/>
            <xs:element name="Csillag" type="csillagTipus"/>
            <xs:element name="Cim" type="cimTipus"/>
            <xs:element name="Foszakacs" type="foszakacsTipus"/>
            <xs:element name="Szakacsok" type="szakacsokTipus" minOccurs="0"/>
            <xs:element name="Gyakornokok" type="gyakornokokTipus" minOccurs="0"/>
            <xs:element name="Vendegek" type="vendegekTipus" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="EKod" type="kodTipus" use="required"/>
    </xs:complexType>

    <!-- ========= Gyökérelem ========= -->

    <xs:element name="PHRO7R_Vendeglatas">
        <xs:complexType>
            <xs:sequence>
                <!-- lehet több Étterem is, de a példában egy van -->
                <xs:element name="Etterem" type="etteremTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== nyakosandor/PHRO7RWebXML/PHRO7R_1015/PHRO7R_XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<PHRO7R_Vendeglatas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PHRO7R_XMLSchemaGPT.xsd">

    <Etterem EKod="EK001">
        <Nev>Régi Vigadó Étterem</Nev>
        <Csillag>5</Csillag>
        <Cim>
            <Varos>Debrecen</Varos>
            <Utca>Nagyerdei park</Utca>
            <Hazszam>1</Hazszam>
        </Cim>
        <Foszakacs FKod="FK001">
            <Nev>Farkas Dániel</Nev>
            <Eletkor>41</Eletkor>
            <Vegzettseg>Kulináris Akadémia</Vegzettseg>
            <Vegzettseg>Nordic Chef School</Vegzettseg>
        </Foszakacs>
        <Szakacsok>
            <Szakacs SzKod="SZ001">
                <Nev>Molnár Lőrinc</Nev>
                <Reszleg>Hidegkonyha</Reszleg>
                <Vegzettseg>Gasztro technikus</Vegzettseg>
                <Vegzettseg>Nordic Chef School</Vegzettseg>
            </Szakacs>
        </Szakacsok>
        <Gyakornokok>
            <Gyakornok GyKod="GY001">
                <Nev>Horváth Bence</Nev>
                <Gyakorlat>Alap konyhai rotáció</Gyakorlat>
                <Kezdete>2025-01-01</Kezdete>
                <Idotartama>6</Idotartama>
                <Muszak>Délelőtt</Muszak>
                <Muszak>Éjszaka</Muszak>
            </Gyakornok>
            <Gyakornok GyKod="GY002">
                <Nev>Sárközi Nóra</Nev>
                <Gyakorlat>Cukrászati asszisztencia</Gyakorlat>
                <Kezdete>2025-02-15</Kezdete>
                <Idotartama>4</Idotartama>
                <Muszak>Délután</Muszak>
            </Gyakornok>
        </Gyakornokok>
        <Vendegek>
            <Vendeg VKod="VK001">
                <Nev>Szilágyi Imre</Nev>
                <Eletkor>24</Eletkor>
                <Cim>
                    <Varos>Győr</Varos>
                    <Utca>Árpád út</Utca>
                    <Hazszam>18</Hazszam>
                </Cim>
                <Rendelesek>
                    <Rendeles>
                        <Osszeg>18500</Osszeg>
                        <Etel>Garnélás rizottó</Etel>
                    </Rendeles>
                </Rendelesek>
            </Vendeg>
        </Vendegek>
    </Etterem>

    <Etterem EKod="EK002">
        <Nev>Calico Jack Pub</Nev>
        <Csillag>5</Csillag>
        <Cim>
            <Varos>Debrecen</Varos>
            <Utca>Bem tér</Utca>
            <Hazszam>15</Hazszam>
        </Cim>
        <Foszakacs FKod="FK002">
            <Nev>Lakatos Andor</Nev>
            <Eletkor>33</Eletkor>
            <Vegzettseg>Le Cordon Vert</Vegzettseg>
        </Foszakacs>
        <Szakacsok>
            <Szakacs SzKod="SZ002">
                <Nev>Szűcs Bence</Nev>
                <Reszleg>Csárda konyha</Reszleg>
                <Vegzettseg>Konyhamester</Vegzettseg>
                <Vegzettseg>Le Cordon Vert</Vegzettseg>
            </Szakacs>
            <Szakacs SzKod="SZ003">
                <Nev>Pintér András</Nev>
                <Reszleg>Tűzhely</Reszleg>
                <Vegzettseg>Szakács</Vegzettseg>
                <Vegzettseg>Kulináris Akadémia</Vegzettseg>
            </Szakacs>
        </Szakacsok>
        <Gyakornokok>
            <Gyakornok GyKod="GY003">
                <Nev>Balogh Milán</Nev>
                <Gyakorlat>Melegkonyhai rotáció</Gyakorlat>
                <Kezdete>2025-03-10</Kezdete>
                <Idotartama>10</Idotartama>
                <Muszak>Délelőtt</Muszak>
            </Gyakornok>
        </Gyakornokok>
        <Vendegek>
            <Vendeg VKod="VK002">
                <Nev>Fülöp Eszter</Nev>
                <Eletkor>31</Eletkor>
                <Cim>
                    <Varos>Szeged</Varos>
                    <Utca>Tisza Lajos körút</Utca>
                    <Hazszam>5</Hazszam>
                </Cim>
                <Rendelesek>
                    <Rendeles>
                        <Osszeg>22400</Osszeg>
                        <Etel>Sertésszűz Wellington</Etel>
                    </Rendeles>
                </Rendelesek>
            </Vendeg>
        </Vendegek>
    </Etterem>

</PHRO7R_Vendeglatas>

=== nyakosandor/PHRO7RWebXML/PHRO7R_1015/PHRO7R_XMLgpt.xml
<?xml version="1.0" encoding="UTF-8"?>
<PHRO7R_Vendeglatas
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="PHRO7R_XMLSchemaGPT.xsd">
    <Etterem EKod="E001">
        <Nev>Aranykanal Etterem</Nev>
        <Csillag>4</Csillag>
        <Cim>
            <Varos>Budapest</Varos>
            <Utca>Fo utca</Utca>
            <Hazszam>10</Hazszam>
        </Cim>

        <Foszakacs FKod="F001">
            <Nev>Kiss Jozsef</Nev>
            <Eletkor>45</Eletkor>
            <!-- Vegzettseg többszörös értékű attribútum -->
            <Vegzettseg>Szakacs mester</Vegzettseg>
            <Vegzettseg>Vendeglato technikus</Vegzettseg>
        </Foszakacs>

        <Szakacsok>
            <Szakacs SzKod="SZ001">
                <Nev>Nagy Anna</Nev>
                <Reszleg>Melegkonyha</Reszleg>
                <Vegzettseg>Szakacs</Vegzettseg>
            </Szakacs>
            <Szakacs SzKod="SZ002">
                <Nev>Toth Peter</Nev>
                <Reszleg>Hidegkonyha</Reszleg>
                <Vegzettseg>Cukrasz</Vegzettseg>
            </Szakacs>
        </Szakacsok>

        <Gyakornokok>
            <Gyakornok GyKod="GY001">
                <Nev>Kovacs Lilla</Nev>
                <Gyakorlat>Nyari szakmai gyakorlat</Gyakorlat>
                <Kezdete>2025-06-15</Kezdete>
                <Idotartama>60</Idotartama>
                <!-- Muszak többszörös értékű attribútum -->
                <Muszak>Delelott</Muszak>
                <Muszak>Delutan</Muszak>
            </Gyakornok>
        </Gyakornokok>

        <Vendegek>
            <Vendeg VKod="V001">
                <Nev>Szabo Marton</Nev>
                <Eletkor>32</Eletkor>
                <Cim>
                    <Varos>Budapest</Varos>
                    <Utca>Kossuth Lajos utca</Utca>
                    <Hazszam>5</Hazszam>
                </Cim>
                <Rendelesek>
                    <Rendeles>
                        <Osszeg>4500</Osszeg>
                        <Etel>Marhaporkolt galuskaval</Etel>
                    </Rendeles>
                    <Rendeles>
                        <Osszeg>1800</Osszeg>
                        <Etel>Somloi galuska</Etel>
                    </Rendeles>
                </Rendelesek>
            </Vendeg>

            <Vendeg VKod="V002">
                <Nev>Nemeth Eva</Nev>
                <Eletkor>27</Eletkor>
                <Cim>
                    <Varos>Budapest</Varos>
                    <Utca>Petofi utca</Utca>
                    <Hazszam>22</Hazszam>
                </Cim>
                <Rendelesek>
                    <Rendeles>
                        <Osszeg>3200</Osszeg>
                        <Etel>Rantott sajt rizzsel</Etel>
                    </Rendeles>
                </Rendelesek>
            </Vendeg>
        </Vendegek>
    </Etterem>
</PHRO7R_Vendeglatas>
