=== nyakosandor/PHRO7RWebXML/PHRO7R_1008/PHRO7R_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:gYear"/>
    </xs:simpleType>

    <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{6}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="t[1-9][0-9]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="igenNemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen"/>
            <xs:enumeration value="nem"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="stringTipus">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="szemeszterTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Å‘sz"/>
            <xs:enumeration value="tavasz"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="kreditTipus">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>

    <xs:simpleType name="napTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="hetfo"/>
            <xs:enumeration value="kedd"/>
            <xs:enumeration value="szerda"/>
            <xs:enumeration value="csutortok"/>
            <xs:enumeration value="pentek"/>
            <xs:enumeration value="vizsgaidoszak"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idoTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-1][0-9]|2[0-3]):[0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="hallgato">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nev" type="stringTipus"/>
                <xs:element name="neptun" type="egyetemTipus"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="targyTipus">
        <xs:sequence>
            <xs:element name="nev" type="stringTipus"/>
            <xs:element name="kod" type="stringTipus"/>
            <xs:element name="kredit" type="kreditTipus"/>
            <xs:element name="tipus" type="stringTipus"/>
            <xs:element name="kovetelmeny" type="stringTipus"/>
            <xs:element name="allapot" type="stringTipus"/>
            <xs:element name="idopont">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nap" type="napTipus"/>
                        <xs:element name="tol" type="idoTipus"/>
                        <xs:element name="ig" type="idoTipus"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="oktato" type="stringTipus" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="idTipus" use="required"/>
        <xs:attribute name="jovahagyas" type="igenNemTipus" use="required"/>
    </xs:complexType>

    <xs:element name="targyak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="targy" type="targyTipus" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato"/>
                
                <xs:element name="felev">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ev" type="tanevTipus"/>
                            <xs:element name="szemeszter" type="szemeszterTipus"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element ref="targyak"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== nyakosandor/PHRO7RWebXML/PHRO7R_1008/PHRO7R_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>
<kurzusfelvetel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="PHRO7R_kurzusfelvetel.xsd">
    <hallgato>
        <nev>Nyakó Sándor</nev>
        <neptun>PHRO7R</neptun>
    </hallgato>
    <felev>
        <ev>2025</ev>
        <szemeszter>ősz</szemeszter>
    </felev>
    <targyak>
        <targy id="t1" jovahagyas="nem">
            <nev>Testnevelés 2.</nev>
            <kod>ETTESME2</kod>
            <kredit>0</kredit>
            <tipus>kollokvium</tipus>
            <kovetelmeny>Aláírás megszerzése</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>hetfo</nap>
                <tol>00:00</tol>
                <ig>00:00</ig>
            </idopont>
        </targy>
        <targy id="t2" jovahagyas="nem">
            <nev>Számítástechnika szigorlat</nev>
            <kod>GEIAL300-B2</kod>
            <kredit>0</kredit>
            <tipus>szigorlat</tipus>
            <kovetelmeny>Szigorlat</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>vizsgaidoszak</nap>
                <tol>00:00</tol>
                <ig>00:00</ig>
            </idopont>
        </targy>
        <targy id="t3" jovahagyas="nem">
            <nev>Mesterséges intelligencia alapok</nev>
            <kod>GEIAK130-B2</kod>
            <kredit>5</kredit>
            <tipus>kollokvium</tipus>
            <kovetelmeny>Kollokvium</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>kedd</nap>
                <tol>10:00</tol>
                <ig>11:30</ig>
            </idopont>
            <oktato>Kunné Dr. Tamás Judit</oktato>
        </targy>
        <targy id="t4" jovahagyas="nem">
            <nev>Windows rendszergazda</nev>
            <kod>GEIAL30A-B2</kod>
            <kredit>5</kredit>
            <tipus>kollokvium</tipus>
            <kovetelmeny>Kollokvium</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>kedd</nap>
                <tol>08:00</tol>
                <ig>09:30</ig>
            </idopont>
            <oktato>Dr. Wagner György</oktato>
        </targy>
        <targy id="t5" jovahagyas="nem">
            <nev>Web technológiák 1.</nev>
            <kod>GEIAL331-B2</kod>
            <kredit>5</kredit>
            <tipus>kollokvium</tipus>
            <kovetelmeny>Kollokvium</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>hetfo</nap>
                <tol>10:00</tol>
                <ig>11:30</ig>
            </idopont>
            <oktato>Agárdi Anita</oktato>
        </targy>
        <targy id="t6" jovahagyas="nem">
            <nev>Mobil programozási alapok</nev>
            <kod>GEIAL335-B2</kod>
            <kredit>5</kredit>
            <tipus>kollokvium</tipus>
            <kovetelmeny>Kollokvium</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>hetfo</nap>
                <tol>16:00</tol>
                <ig>17:30</ig>
            </idopont>
            <oktato>Agárdi Anita</oktato>
        </targy>
        <targy id="t7" jovahagyas="nem">
            <nev>Angol műszaki szaknyelv 1.</nev>
            <kod>MEIOKMUSZAN1</kod>
            <kredit>0</kredit>
            <tipus>aláírás</tipus>
            <kovetelmeny>Aláírás megszerzése</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>hetfo</nap>
                <tol>12:00</tol>
                <ig>13:30</ig>
            </idopont>
            <oktato>Lévai-Asztalos Erzsébet</oktato>
        </targy>
        <targy id="t8" jovahagyas="nem">
            <nev>Elektrotechnika-elektronika</nev>
            <kod>GEVEE050-B2</kod>
            <kredit>5</kredit>
            <tipus>kollokvium</tipus>
            <kovetelmeny>Kollokvium</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>hetfo</nap>
                <tol>08:00</tol>
                <ig>09:30</ig>
            </idopont>
            <oktato>Szabó Norbert</oktato>
        </targy>
        <targy id="t9" jovahagyas="nem">
            <nev>Webes adatkezelő környezetek</nev>
            <kod>GEIAL32K-B2</kod>
            <kredit>5</kredit>
            <tipus>kollokvium</tipus>
            <kovetelmeny>Kollokvium</kovetelmeny>
            <allapot>Leadás</allapot>
            <idopont>
                <nap>szerda</nap>
                <tol>08:00</tol>
                <ig>11:30</ig>
            </idopont>
            <oktato>Dr. Bednarik László</oktato>
        </targy>
    </targyak>
</kurzusfelvetel>
