<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mozi [
    <!ELEMENT mozi (film*)>
    <!ELEMENT film (rendezo+, szinesz+, iro+)>
    <!ATTLIST film
        id ID #REQUIRED
        mufaj (horror | drama | vigjatek) #REQUIRED
    >

    <!ELEMENT rendezo (vezetorendezo?, segedrendezo?)>
    <!ATTLIST rendezo id ID #IMPLIED nev CDATA #IMPLIED>
    <!ELEMENT vezetorendezo EMPTY>
    <!ELEMENT segedrendezo EMPTY>

    <!ELEMENT szinesz (gyerekszinesz|musicalszinesz|szinkronszinesz)*>
    <!ATTLIST szinesz id ID #IMPLIED nev CDATA #IMPLIED>
    <!ELEMENT gyerekszinesz EMPTY>
    <!ELEMENT musicalszinesz EMPTY>
    <!ELEMENT szinkronszinesz EMPTY>

    <!ELEMENT iro (foiro|tarsiro)*>
    <!ATTLIST iro id ID #IMPLIED>
    <!ELEMENT foiro EMPTY>
    <!ELEMENT tarsiro EMPTY>
]>
<mozi>
    <film id="txn_nxm_2jb" mufaj="horror">
        <rendezo id="nzk_4xm_2jb" nev="alex" />
        <szinesz id="u5g_4xm_2jb" nev="Madison_Ivy" />
        <szinesz id="a">
            <gyerekszinesz />
            <musicalszinesz />
            <szinkronszinesz />
        </szinesz>
        <iro id="trv_4xm_2jb" />
    </film>
    <film id="abc_2jb" mufaj="drama">
        <rendezo id="rnd_2jb">
            <vezetorendezo />
            <segedrendezo />
        </rendezo>
        <iro id="iro_2jb">
            <foiro />
            <tarsiro />
        </iro>
    </film>
</mozi>

